### ISSUE TITLE
[Email] images not loading correctly in mailchimp emails?

### ISSUE THREAD

**Issue by jessesquires** [techworkersco/techworkersco.github.io#25]
Not sure how to fix this.

Relevant docs:
https://mailchimp.com/help/rss-merge-tags/#Item_tags

Maybe add `*|RSSITEM:IMAGE|*` to the template?

And include in the RSS feed:

```html
<media:content url="http://link/to/example.jpg" medium="image"> 
```

**Comment by anaulin** [comment]
Looking at the source for the test email, I think the problem is that the image URLs in the RSS feed are relative to the site (which is how I made the image links in the first place):

![Screen Shot 2020-04-30 at 9 48 29 PM](https://user-images.githubusercontent.com/6729309/80782826-85edd680-8b2c-11ea-9429-113b278baa44.png)

So I wonder if this will "fix itself" if we make sure to use absolute image URLs in the posts. I'll tweak the latest Volume 1 content and do another test, and see if that improves things.

**Comment by anaulin** [comment]
Digging further, it looks like most links in the RSS feed are created correctly, relative to the main URL, but not the ones for the header image, so maybe the best way to tweak this is by modifying the `image.html` template.

![Screen Shot 2020-04-30 at 10 06 16 PM](https://user-images.githubusercontent.com/6729309/80783570-0a415900-8b2f-11ea-93f8-21ba0f6459e4.png)

**Comment by anaulin** [comment]
Ok, now the img URL is complete in the production RSS feed:

![Screen Shot 2020-04-30 at 10 20 30 PM](https://user-images.githubusercontent.com/6729309/80784137-d9622380-8b30-11ea-91ae-c601e91343a3.png)

But will MailChimp blend? 🤔

**Comment by anaulin** [comment]
It will! (Also improved the subject line thing.)

![Screen Shot 2020-04-30 at 10 27 04 PM](https://user-images.githubusercontent.com/6729309/80784393-c2700100-8b31-11ea-9e3f-99a639edef90.png)

**Comment by jessesquires** [comment]
hell yes. nice work @anaulin 🎉
