### ISSUE TITLE
Improve newsletter email display on mobile (esp. bigger, more legible font)

### ISSUE THREAD

**Issue by anaulin** [techworkersco/techworkersco.github.io#36]
@stationaery reports that the MailChimp-emitted email looks pretty bad on mobile. I checked and I concur: on mobile it seems to be still as wide as on desktop, which leads to teeny-tiny squeezed-together font.

Would be good to improve this. These days, many (most?) of the readers will be seeing this email on mobile.

**Comment by jessesquires** [comment]
I'm not sure what's causing this.

We currently don't have this problem with Swift Weekly (it sizes correctly on mobile), but I don't have access to the settings used there.

**Comment by anaulin** [comment]
I glanced at the MailChimp template but didn't see anything obvious. I wonder if the RSS itself includes some formatting?

For reference, this is a screenshot of the newsletter on my phone:
![Screenshot_20200502-191344](https://user-images.githubusercontent.com/6729309/80897031-852e7f00-8ca9-11ea-87fb-726be076a670.png)

Compare with some other newsletter on my phone:
![Screenshot_20200502-191421](https://user-images.githubusercontent.com/6729309/80897025-7778f980-8ca9-11ea-821f-86779d936ba8.png)

**Comment by anaulin** [comment]
MailChimp's campaign preview also shows it as not being well-formatted on mobile:
![Screen Shot 2020-05-02 at 7 21 30 PM](https://user-images.githubusercontent.com/6729309/80897105-506ef780-8caa-11ea-8e11-fc078b56c946.png)

**Comment by jessesquires** [comment]
> I wonder if the RSS itself includes some formatting?

Hm... maybe? But the mobile site looks fine on my phone...

**Comment by anaulin** [comment]
The guess about the RSS seemed like an unlikely thing to me too. I wonder if the template needs to have something to adapt to mobile better?

**Comment by jessesquires** [comment]
>  I wonder if the template needs to have something to adapt to mobile better?

Probably. You can go through the "Edit" flow. On the "design" section, you can specify all the different styles for headings, etc.

When I set everything up yesterday, all I did was update the link colors, so we might be able to tweak this.

**Comment by stationaery** [comment]
Incidentally, the Nadia Eghbal newsletter is a bag of gems - I
highly recommend it

**Comment by jessesquires** [comment]
Ok folks! This is fixed!

Apparently, we completely exceeded the testing email sends for this campaign. I thought that was a temporary limit the other week and that we'd be able to send more tests later. However, it appears that it's a hard limit on MailChimp -- so, no more test emails for us. Ever. 🤷‍♂️ 

### Anyway, the notable changes are:

- Fixed mobile (I actually didn't do anything specific here. I think this was fixed when I checked the setting box to have mailchimp resize images. 🤷‍♂️ something something computers.)
- Refined styles: colors, font sizes, spacing, etc.
- Removed the date beneath the issue title. MailChimp's derpy-ass formatting wasn't working. However, I realized that this was redundant anyway. The sent/received date is part of the email already, so no need to repeat it.
- Cleaned up the footer text.
- Added a link to our twitter in the footer. 
- Removed the email link in the footer. This was also redundant since the email is from us, and readers can simply reply.

## Some screenshots: 

### Desktop

<img width="921" alt="Screen Shot 2020-05-13 at 6 30 44 PM" src="https://user-images.githubusercontent.com/2301114/81883492-37880100-954a-11ea-8a23-ce5b074f81bc.png">

<img width="924" alt="Screen Shot 2020-05-13 at 6 30 54 PM" src="https://user-images.githubusercontent.com/2301114/81883507-41116900-954a-11ea-9cdc-c31c7fa86ebe.png">

<img width="924" alt="Screen Shot 2020-05-13 at 6 31 09 PM" src="https://user-images.githubusercontent.com/2301114/81883518-466eb380-954a-11ea-8f7c-2fcf2c7a8061.png">

<img width="929" alt="Screen Shot 2020-05-13 at 6 31 18 PM" src="https://user-images.githubusercontent.com/2301114/81883522-4969a400-954a-11ea-85ab-6b7e4eba9d40.png">

### Mobile

<img width="558" alt="Screen Shot 2020-05-13 at 6 31 32 PM" src="https://user-images.githubusercontent.com/2301114/81883537-51294880-954a-11ea-9262-7dab0a489fe7.png">

<img width="470" alt="Screen Shot 2020-05-13 at 6 31 46 PM" src="https://user-images.githubusercontent.com/2301114/81883541-54243900-954a-11ea-870b-46d1bb9cce08.png">

<img width="481" alt="Screen Shot 2020-05-13 at 6 32 02 PM" src="https://user-images.githubusercontent.com/2301114/81883544-56869300-954a-11ea-9aa9-d328fc597bef.png">

<img width="455" alt="Screen Shot 2020-05-13 at 6 32 13 PM" src="https://user-images.githubusercontent.com/2301114/81883550-59818380-954a-11ea-8cdb-faff7e65bb4e.png">

**Comment by anaulin** [comment]
Beautiful, thanks Jesse! 🎉 😻

**Comment by stationaery** [comment]
🎉! Nice work!

Also, wtƒ! I don't get it. Why limit tests forever not just for a duration
of time? At least, can we ask MailChimp to re-set the tests?
