### ISSUE TITLE
We knew Mailchimp would either fail us or betray us one day- it time to move.

### ISSUE THREAD

**Issue by stationaery** [techworkersco/techworkersco.github.io#376]
Saw this the other day:
![538676425e08bfc67ed85846910daee4552cbbe563ad2a2d0a1459715142e35a](https://user-images.githubusercontent.com/8990653/222292956-326d1abd-1899-4b74-87b2-95063aef93e3.png)

If I understand this correctly, Mailchimp will not grandfather in our account and instead will cut our list of ~1,700 down to 500. This was perhaps a matter of time, as the free limit has been 2,000.

So, time to migrate away from Mailchimp... and move to... [Action Network](https://actionnetwork.org/)? 

This will require some programming work so our current listening/scraping setup for AN. This will also involve some design and layout work to create a custom theme for emails too. 

A bonus: this is a great opportunity to tag/segment our list so we can get serious about organizing, creating what AN calls "ladders" for people to engage with us in various ways eg subscribing, submitting tips, contributing, editing, conducting interviews, etc.

**Comment by jessesquires** [comment]
I highly doubt they are going to delete contacts, that would be pretty fucked up. It will probably manifest as only sending to the first 500 or something.

> So, time to migrate away from Mailchimp... and move to... [Action Network](https://actionnetwork.org/)?
>
> This will require some programming work so our current listening/scraping setup for AN. This will also involve some design and layout work to create a custom theme for emails too.

I don't know anything about how ActionNetwork works.

I also don't have any capacity to contribute any time to this. However, I can provide technical guidance in terms of how everything currently works so that someone else has all the knowledge they need to do the migration.

As far as the listening/scraping setup goes — MailChimp just grabs the RSS feed that we publish. If another service has similar functionality (whether that's AN or not), there's no work to do in terms of the website. The new service just needs to grab the RSS feed. (We'll still be publishing on the site and generating the RSS feed.)

**Comment by jessesquires** [comment]
RE: technical guidance

I just remembered I wrote a bunch of technical documentation way back and it should all still be mostly up-to-date. So whoever takes this on, you can find the docs here: https://github.com/techworkersco/techworkersco.github.io/blob/master/.github/DOCUMENTATION.md

If there are still questions after reviewing that, I'm happy to answer them.

**Comment by eddywashere** [comment]
Setting up action network right now. It's a manual process to get to a paid account, allowing us to bulk upload our list from Mailchimp over to AN. It is also required to create custom email layouts and send more than 500 emails. It's $10 a month that gets us 10k sends and an additional $1 per 1k email sends after.

In order to send from [news-noreply@techworkerscoalition.org](mailto:news-noreply@techworkerscoalition.org) we'll need to first request this functionality from AN, I can do that. Then we'll update DNS records, which likely the Mailchimp setup had y'all do. 

Does someone have access to let me update things on the DNS side? @jessesquires @stationaery?

**Comment by jessesquires** [comment]
> Does someone have access to let me update things on the DNS side?

I do not. @kidmillions did this for us way back. Not sure if he is active on any of this anymore. Maybe @shushugah has access?

**Comment by stationaery** [comment]
> I highly doubt they are going to delete contacts, that would be pretty fucked up. It will probably manifest as only sending to the first 500 or something.

It seems Mailchimp decided on something in the middle:
<img width="489" alt="Screen Shot 2023-03-11 at 6 04 35 PM" src="https://user-images.githubusercontent.com/8990653/224520151-5a20d70f-7b74-4d9c-ad29-95c7dc369b47.png">

**Comment by jessesquires** [comment]
Not surprised. 😒

**Comment by shushugah** [comment]
@eddywashere I saw you were able to update the DNS record via Netlify, did that work?
