### ISSUE TITLE
Archive: update Volume 1 entries so that no images are above the <!--excerpt-->

### ISSUE THREAD

**Issue by stationaery** [techworkersco/techworkersco.github.io#88]
In https://news.techworkerscoalition.org/archive/ or in each issue (I'm not sure which), make edits so the cover image shows in the archive view

**Comment by jessesquires** [comment]
Actually, I disagree with that -- I think that overloads that page, makes it too busy.

Currently, the ones that are displaying images are odd-ball issues from Volume 1.

I would rather move those images below the `<!--excerpt-->` so that they do not show on the archives page.

(Also, I think that will have strange implications for the "preview text" in the RSS feed and elsewhere.)

**Comment by stationaery** [comment]
> I would rather move those images below the  so that they do
not show on the archives page

I can get with that. I’m coming from a place of wanting the archive to look
organized and accessible. Looking back at it now, the images for the Vol. 1
issues was grabbing my attention and sort of distracting me from other
entries.

**Comment by anaulin** [comment]
Sounds like this issue is resolved. Should we close it? (We can have a separate issue to hide the few images from older issues that show in the archive.)

**Comment by jessesquires** [comment]
@anaulin I think it's ok to keep tracking using this issue. 

I updated the title of this to reflect the changes we want to make.

**Comment by jessesquires** [comment]
looks like there's only 4 issues where this happens, so should be a quick fix.

those entries will not have any preview text, but i think that's ok --- no use spending time trying to perfect Volume 1, which was less structured.
